<div class="entry-edit">
    <fieldset id="my-fieldset">
        <p class="grand-total"><b><?php echo $this->__('Help Tip: How to add a slider to a page')?></b></p>
        <p><?php echo $this->__('You can insert a slider as a widget anywhere!<br />To insert a slider widget, use the following code construction (in versions <b>older than Magento v1.6.0.0</b>, make sure the editor is disabled):<br /><b>{{widget type="advancedslider/widget_slider" unique_id_prefix="slider_1_" slider="1"}}</b><br /><b>unique_id_prefix</b> - the unique prefix for the identifier of a slider container on a page (any string)<br /><b>slider</b> - one of the 5 slider identifiers (Standard, Krista, Nicole, Trisha, Xandra).')?></p>
    </fieldset>
</div>
