<?php
    $image = '<img title="' . $this->__('Schematic representation of the slider') . '" src="' . $previewImageUrl . '" width="150" border="0" />';
?>
<table id="advancedslider_style_description" cellspacing="0" class="form-list box-left">
    <tr>
        <td class="label">
            <label for="style_description"><?php echo $this->__('Description')?></label>
            <div style="margin-top:15px;">
                <?php echo $image; ?>
            </div>
        </td>
        <td class="value">
            <?php echo $description; ?>
        </td>
    </tr>
</table>
