<?php
/**
 * Magmodules.eu
 * http://www.magmodules.eu
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magmodules.eu so we can send you a copy immediately.
 *
 * @category    Magmodules
 * @package     Magmodules_Kiyohsnippets
 * @author      Magmodules <info@magmodules.eu)
 * @copyright   Copyright (c) 2014 (http://www.magmodules.eu)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

if($this->getSnippetsEnabled()) {
	$snippets  = $this->getSnapshopRequest();
	$kiyohlink  = $this->getKiyohLink();
	$shopname   = $this->getShopname();
	if($snippets) { 
?>
	<div class="kiyoh-shop-snippets">
		<?php echo $this->getKiyohStars($snippets['avg']); ?>
		<div class="kiyoh-schema" itemscope="itemscope" itemtype="http://schema.org/Product">
			<meta itemprop="name" content="<?php echo $shopname; ?>">
			<div itemprop="aggregateRating" itemscope="itemscope" itemtype="http://schema.org/AggregateRating">
				<meta itemprop="bestRating" content="100">
				<p><?php echo Mage::helper('kiyohsnippets')->__('Rating %s based on %s customer reviews', '<span itemprop="ratingValue">' . $snippets['avg'] . '</span>%', '<span itemprop="reviewCount">' . $snippets['qty'] . '</span>') ?> <?php echo $kiyohlink; ?> </p>
			</div>
		</div>
	</div>	
	<?php } ?>
<?php } ?>
