<?php $direct = Mage::getModel('paymentsensegateway/direct'); ?>
<?php $_code=$this->getMethodCode(); ?>
<?php $route = $this->getRequest()->getRequestedRouteName(); if($route == 'onestepcheckout'){ $fieldCode = '['.$_code.']'; } else { $fieldCode = ''; }?>

<?php if ($direct->getConfigData('mode') == Paymentsense_Paymentsensegateway_Model_Source_PaymentMode::PAYMENT_MODE_HOSTED_PAYMENT_FORM) {?>
	<fieldset class="form-list">
		<ul id="payment_form_<?php echo $_code ?>" style="display:none">
	        <li>
	            <?php echo $this->__('Usted será redirigido a una página segura donde usted puede terminar su pago.') ?>
	        </li>
	        <li class='notice-msg'>
	        	<?php echo $this->__('Por favor, no intente hacer clic en el botón "BACK" en su navegador una vez que se redirija a la página de PagueloFacil para completar su pago. Si usted necesita cambiar su orden, usted puede hacerlo antes de realizar su pago.') ?>
	        </li>
	    </ul>
	</fieldset>
<?php } else {?>
	<fieldset class="form-list">
	    <ul id="payment_form_<?php echo $_code; ?>" style="display:none">	    	
	    	<li style="display:none;">
				<img alt="<?php echo $this->__('PagueloFacil logo'); ?>" src="<?php echo $this->getSkinUrl('images/paymentsense.gif'); ?>">
			</li>
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_owner"><?php echo $this->__('Nombre en la Tarjeta') ?> <span class="required">*</span></label><br/>
	                <input type="text" title="<?php echo $this->__('Name On Card') ?>" class="input-text required-entry validate-length maximum-length-16" id="<?php echo $_code; ?>_cc_owner" name="payment<?php echo $fieldCode; ?>[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>"/>
	            </div>
	        </li>
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_number"><?php echo $this->__('Numero de la Tarjeta') ?> <span class="required">*</span></label><br/>
	                <input type="text" maxlength="16" id="<?php echo $_code; ?>_cc_number" name="payment<?php echo $fieldCode; ?>[cc_number]" title="<?php echo $this->__('Card Number') ?>" class="input-text required-entry validate-digits validate-length maximum-length-16 validate-cc-number" value=""/>
	            </div>
	        </li>
	        <li>
	         	<label for="<?php echo $_code; ?>_expiration"><?php echo $this->__('Dia de Expriracion') ?> <span class="required">*</span></label><br/>
	         	<div class="input-box">
	                <div class="v-fix">
	                <select id="<?php echo $_code; ?>_expiration" name="payment<?php echo $fieldCode; ?>[cc_exp_month]" class="month validate-cc-exp required-entry">
	                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
	                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
	                    <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
	                <?php endforeach ?>
	                </select>
	                </div>
	                
	                <div class="v-fix">
	                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
	                <select id="<?php echo $_code; ?>_expiration_yr" name="payment<?php echo $fieldCode; ?>[cc_exp_year]" class="year required-entry">
	                <?php foreach ($this->getCcYears() as $k=>$v): ?>
	                    <option value="20<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
	                <?php endforeach ?>
	                </select>
	                </div>
	            </div>
	        </li>
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_cid"><?php echo $this->__('CVV') ?> <span class="required">*</span></label><br/>
	                <div class="v-fix"><input maxlength="3" type="text" title="<?php echo $this->__('CVV') ?>" class="input-text required-entry validate-digits validate-length minimum-length-3 maximum-length-3" id="<?php echo $_code; ?>_cc_cid" name="payment<?php echo $fieldCode; ?>[cc_cid]" style="width:50px;" value=""/></div>
	                &nbsp;
	                <a href="#" class="cvv-what-is-this"><?php echo $this->__('Que es esto?') ?></a>
	            </div>
	        </li>
	        <li>
	            <div class="input-box">
	            	<img width="231" height="48" alt="<?php echo $this->__('PagueloFacil logo'); ?>" src="<?php echo $this->getSkinUrl('images/verified_logos.png'); ?>">
	            </div>	        
	        </li>
	        <li>
	         	<!-- <label for="<?php //echo $_code; ?>_cc_ss_start_month"><?php //echo $this->__('Dia de Adquisicion') ?></label><br /> -->
	         	<div class="input-box">
	                <div class="v-fix">
	                <input type="hidden" id="<?php echo $_code; ?>_cc_ss_start_month" name="payment<?php echo $fieldCode; ?>[cc_ss_start_month]" class="month" value="01" />
	                
	                </div>
	                <div class="v-fix">
	                <?php $_ccStartYear = $this->getInfoData('cc_ss_start_year') ?>
	                <input type="hidden" id="<?php echo $_code ?>_cc_ss_start_year" name="payment<?php echo $fieldCode; ?>[cc_ss_start_year]" class="year" value="13" />
	                
	                </div>
	            </div>
	        </li>
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_ss_issue"></label><br />
	                <div class="v-fix"><input type="hidden" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-digits validate-length maximum-length-2" id="<?php echo $_code ?>_cc_ss_issue" name="payment<?php echo $fieldCode; ?>[cc_ss_issue]" style="width:50px;" value="00" /></div>
	            </div>
	        </li>
	    </ul>
	</fieldset>
	<?php if($_SERVER['QUERY_STRING'] && $_SERVER['QUERY_STRING'] == "notLoggedin=1"){?>
	<script type="text/javascript">
		var html= '<div style="width: 500px; left: 50%; margin-left: -251px; top: 370px; display: block;position:absolute;" id="popup-onepagecheckout-error" class="wp-one-page-checkout-popup opc"><div class="section active"><div class="step-title"><h2>No ha iniciado sesion</h2><span id="popup-onepagecheckout-error_btn_close" class="number" onclick="closePopup()"></span></div><div class="step a-item" id="popup-onepagecheckout-error_content_html">Necesita iniciar sesion para realizar el pago</div></div></div>';
		$$("body")[0].insert(html);
		function closePopup(){
			document.getElementById("popup-onepagecheckout-error").style.display = 'none';
		}
	</script>
	<?php }?>
<?php }?>