<?php 
	//$point = $_SESSION['point'];
	$session = Mage::getSingleton('customer/session');
	if($session->isLoggedIn()) 
	{
		$customer = $session->getCustomer();
		
		echo "Hello! ";
		echo $customer->getName().'<br>';
	} 
	?>
	<span style="color: red; font-weight: bold;"><?php echo "Your Given Quetion Ans(Answers) is(are) :"?></span><br/>
	<?php 
	$id 			= (int) $this->getRequest()->getParam('id');
	$item 			= Mage::getModel('module/module')->load($id);
	echo $quizvideotitle = $item->getQuizvideoTitle();
	$collection		= Mage::getModel('quetions/quetions')->getCollection();
	
	$collection->addFilter('quizvideotitle',array('in' => $quizvideotitle));
	$qcount= count($collection);
	$j				= count($collection);//==2
	$moduleid 		= $item->getModuleId();///6
	$i				= $moduleid;
	
		for ($i=1; $i <= $j ; $i++)
		{
			$queid += 1; 
			$moduleid+1;
			$moduleid++ ;
			if($_POST[$moduleid])
			{
				foreach ($collection as $demo) 
				{
					$getpoint=$demo->getPoint();		
					$right 	= $demo['right_answer'];
					if($_POST[$moduleid]==$right)
					{
						$right = $_POST[$moduleid]==$right;
						if($right)
						{
							$getpoint;
						}
						 $countTotal += $getpoint;   
					}
				}
			}
		}



	 $total =  $countTotal;
	 $total =number_format($total, 2, '.', '');
 
	// if client need result in percentage then we can use below code so for this comment above two line and uncomment below lines 
	/*
	$totalpoint=$collection->addFieldToSelect('point');
	$sum =0;
	foreach ($totalpoint as $k=>$v):
	    $sum = $sum+$v['point'];
	endforeach;
	$sum;
	$total =  $countTotal*100/$sum;
	 $total =number_format($total, 2, '.', '');
	*/
 		$model = Mage::getModel('result/result');
		
        $model->setName($customer->getName())
        	  ->setEmail($customer->getEmail())
			  ->setQuizvideo($quizvideotitle)
        	  ->setCreatedTime(now())
        	  ->setUpdateTime(now())
        	  ->setPoint($total);
		$model->save();
		
	echo Mage::getSingleton('adminhtml/session')->addSuccess(Mage::helper('adminhtml')->__('Your Result is successfully saved.'));

?>
<br />
<span style="color: red; font-weight:bold; text-transform: capitalize;"><?php echo $this->__('Note:') ?></span>
<span style="font-weight:bold; text-transform: capitalize; color: blue;"><?php echo $this->__('If your answer is wrong then Right message will not display') ?></span>

